#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the permutationEquation function below.
def permutationEquation(p,n):
    new_list = []
    for i in range(len(p)):
        for j in range(len(p)):
            if p[j]==i+1:
                for k in range(len(p)):
                    if p[k]==j+1:
                        new_list.append(k+1)
    return new_list

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    p = list(map(int, input().rstrip().split()))

    result = permutationEquation(p,n)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
